name: Build and Deploy - 2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Publish
      run: dotnet publish StudentPortal.csproj -c Release -o ./output

    - name: Stop IIS
      shell: powershell
      run: |
        try { Stop-WebAppPool -Name "DefaultAppPool" } catch {}
        Start-Sleep -Seconds 5
        try { Stop-WebSite -Name "Studentportal" } catch {}
        Start-Sleep -Seconds 3
        & taskkill /F /IM w3wp.exe 2>&1 | Out-Null
        Start-Sleep -Seconds 3
        exit 0

    - name: Deploy files
      shell: powershell
      run: |
        Copy-Item -Path "./output/*" -Destination "C:\inetpub\wwwroot\StudentPortal\" -Recurse -Force

    - name: Start IIS
      shell: powershell
      run: |
        Start-WebAppPool -Name "DefaultAppPool"
        Start-WebSite -Name "Studentportal"
        Write-Host "Deployment done!"
