name: Build and Deploy - 2 

on:
  workflow_dispatch:
  push:
    branches:
      - main  
    

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Publish
      run: dotnet publish StudentPortal.csproj -c Release -o ./output

    - name: Stop IIS
      shell: powershell
      run: iisreset /stop

    - name: Deploy files
      shell: powershell
      run: |
        Copy-Item -Path "./output/*" -Destination "C:\inetpub\wwwroot\StudentPortal\" -Recurse -Force

    - name: Start IIS
      shell: powershell
      run: iisreset /start
